asoc: codecs: aw882xx: Import the missing header files
../techpack/audio/asoc/codecs/aw882xx/src/aw882xx_device.c:322:11: error: use of undeclared identifier 'MISC_DYNAMIC_MINOR'
        .minor = MISC_DYNAMIC_MINOR,
                 ^
../techpack/audio/asoc/codecs/aw882xx/src/aw882xx_device.c:320:26: error: variable has incomplete type 'struct miscdevice'
static struct miscdevice misc_algo_auth = {
                         ^
../techpack/audio/asoc/codecs/aw882xx/src/aw882xx_device.c:320:15: note: forward declaration of 'struct miscdevice'
static struct miscdevice misc_algo_auth = {
              ^
../techpack/audio/asoc/codecs/aw882xx/src/aw882xx_device.c:330:8: error: implicit declaration of function 'misc_register' [-Werror,-Wimplicit-function-declaration]
        ret = misc_register(&misc_algo_auth);
              ^
../techpack/audio/asoc/codecs/aw882xx/src/aw882xx_device.c:330:8: note: did you mean 'bus_register'?
../include/linux/device/bus.h:122:25: note: 'bus_register' declared here
extern int __must_check bus_register(struct bus_type *bus);
                        ^
../techpack/audio/asoc/codecs/aw882xx/src/aw882xx_device.c:341:2: error: implicit declaration of function 'misc_deregister' [-Werror,-Wimplicit-function-declaration]
        misc_deregister(&misc_algo_auth);
        ^